apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium.yaml
  - kyverno.yaml

  - strimzi.yaml
  - cnpg.yaml
  - crossplane.yaml
  - headlamp.yaml
  - loki.yaml
  - tempo.yaml
  - kube-prometheus-stack.yaml
  - alloy.yaml
