apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium.yaml
  - ingress-nginx.yaml
  - kyverno.yaml
  - strimzi.yaml
  - cnpg.yaml
  - crossplane.yaml
  - headlamp.yaml
  - observability.yaml
