apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crossplane-namespace.yaml
  - kyverno-namespace.yaml
  - strimzi-namespace.yaml
  - cnpg-namespace.yaml
  - kafka-namespace.yaml
  - headlamp-namespace.yaml
  - observability-namespace.yaml
